### ISSUE TITLE
[UAVCAN/CAN] STM32 bxCAN triggers an assertion failure on transmission

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/platform_specific_components#27]
Works fine at 1 Mbps, fails at 125 kpbs, presumably because of a rare timing issue in the priority inversion management logic, which is not surprising because it is rather convoluted. Here (tx_mailbox is not correct here):

https://github.com/UAVCAN/platform_specific_components/blob/1513fe7f3ddeb4e6b5a38f1d5954e08b08d42017/stm32/libcanard/bxcan/src/bxcan.c#L604

```gdb
(gdb) bt
#0  chSysHalt (reason=reason@entry=0x80085c0 "bxcan/bxcan.c") at chibios/os/rt/src/chsys.c:212
#1  0x08002248 in __assert_func (line=589, func=<synthetic pointer>, expr=<synthetic pointer>, file=0x80085c0 "bxcan/bxcan.c") at src/os/sys.cpp:68
#2  bxCANPush (iface_index=0 '\000', payload=0x20005790 <main::can_driver+56>, payload_size=8, extended_can_id=276822141, deadline=<optimized out>, 
    current_time=33000360) at bxcan/bxcan.c:589
#3  telega_bootloader::CANDriver<8192u>::poll (this=this@entry=0x20005758 <main::can_driver>, now=...) at src/can.hpp:77
#4  0x08005eac in telega_bootloader::CANDriver<8192u>::pop (this=0x20005758 <main::can_driver>, payload_buffer=...) at src/can.hpp:69
#5  0x08004470 in kocherga::can::detail::V1MainActivity::poll (this=0x20008118 <main::can_node+1056>, reactor=..., uptime=...)
    at kocherga/kocherga/kocherga_can.hpp:1667
#6  0x08001924 in kocherga::can::CANNode::poll (this=0x20007cf8 <main::can_node>, reactor=..., uptime=...) at kocherga/kocherga/kocherga_can.hpp:2289
#7  0x08005f96 in kocherga::detail::Presenter::poll (this=0x20007ad0 <main::boot+24>, uptime=...) at kocherga/kocherga/kocherga.hpp:596
#8  kocherga::Bootloader::poll (this=0x20007ab8 <main::boot>, time_since_boot=...) at kocherga/kocherga/kocherga.hpp:1066
#9  operator() (__closure=<optimized out>) at src/main.cpp:102
#10 0x08007ffc in main () at src/main.cpp:159
(gdb) up 2
#2  bxCANPush (iface_index=0 '\000', payload=0x20005790 <main::can_driver+56>, payload_size=8, extended_can_id=276822141, deadline=<optimized out>, 
    current_time=33000360) at bxcan/bxcan.c:589
589             BXCAN_ASSERT(tx_mailbox < 3U);  // Index check - the value must be correct here
(gdb) info locals
bxcan_base = 0x40006400
error_iface = 0x200097ac <g_error>
input_ok = true
out_status = false
tx_mailbox = <optimized out>
prio_higher = false
input_ok = <optimized out>
out_status = <optimized out>
bxcan_base = <optimized out>
error_iface = <optimized out>
tx_mailbox = <optimized out>
prio_higher = <optimized out>
__func__ = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, 
  <optimized out>, <optimized out>}
AllTME = <optimized out>
tme = {<optimized out>, <optimized out>, <optimized out>}
i = <optimized out>
mb = <optimized out>
scratch_data = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}
```

**Comment by pavel-kirienko** [comment]
FYI @TomDeRybel
